apiVersion: v1
kind: Secret
metadata:
    name: api-service-secret
    namespace: owl
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:ZCYAL6aF24orXuVrYqAbKHWrOyUGVay+C3cERGl0BErIFTgjCEOXro0ZtWQKhUSRjGHMulUDoTcyH5rw,iv:u5W/LPIFAa5mmWNOwOick+3hDrVwXYuNzDHZZKSDNAE=,tag:600IYnVGDfFqFlFYwRz8jA==,type:str]
    FEISHU_APP_SECRET: ENC[AES256_GCM,data:SiGjVWLekQcdj46VHy8CAQTSQicR1umimkz8VZQF66c=,iv:VtoMSS8PTg1dB9H653rLc+cpKS7sCPeghIAKGlm5w68=,tag:ss0uHhzAywsXJxLcCK6klg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:ZIo6R57YH3i4eVg1JG/Gp+j4iPWdi7A=,iv:0t8d8AyVlZEG0+R32Qq2kCYBXtdN6LI/NtZ11CctHjk=,tag:jKn+A/MzKBFxgXH2zWKLFw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:7VMuvB8FWlJKVPY=,iv:iDZygstvPyxNkzBc3d+Vh4+VEs22OrPIN5Li/X1iJRY=,tag:p+abz8IpJcdMKjDGgl3jTA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:2s5BzVQz,iv:WaWg9SIwUyIy7Uh7rwkwin5BFXqcVVy8qddjQz0typo=,tag:9FEYjwRjRSVyAT/I736u3A==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:UZpKbEVD,iv:PerRuGfPKAg5bKDkngi9S+jQGlyjBOls91zIiYyd6cc=,tag:xZf+k8DByimvWN5UhQZLKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VWpDSXpkM21uTXlCR3cr
            MVlJSU1rMElSRkNWRHZMRVJOQm1PWlNiYVJFCmExaGVrcDRGYStwcVZkZmVBenhs
            eUhxOXdST0Q4ZWNTYnIvVU1oWlVLRHcKLS0tIHVCUjgvL2lPUmVCQjBZaFFGNkR2
            YVNSVHAvMlBaYlVYcTNvZE83UVl3TjQKa7mbr45Qpc+60w5nJNvS8HVVMIKdA1L1
            0PSR2Xa+GfgsUw+wr3khDh95jM/9p012GF3r4hZOh+Oqoi905eJ6+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l9qlukrqgdcfvtenn5egqstw4l3lzlc8xup5p4l2vm9x0j84nqrqfaexhz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T06:23:19Z"
    mac: ENC[AES256_GCM,data:kPN0JzT+qlF25KywDSumvSihz0xDJpHFLeMcY8ayVkE61gbFWWPe1IthvtLTh5fjTzuuq07tWcnigsTrRbSwiQanW5Xl3eCeNEo74Cs+sUsZkmbOo2Z6tWFL95DWJkspxINtYRo/6U5L++oeAvWRxXBakcjw6lHsElB8ZHJPMjY=,iv:befsgBwfWsh0OA5xnFxjuvig2xZJTfowkbhzCnr8iJo=,tag:+130aghAnuCM6+enjU+bFA==,type:str]
    version: 3.13.3
