apiVersion: v1
kind: Secret
metadata:
  name: cron-service-secret
  namespace: owl
type: Opaque
stringData:
  POSTGRES_PASSWORD: "123456"
  DATABASE_URL: postgresql://admin:123456@172.23.0.10:5432/owl?schema=public
  REDIS_PASSWORD: "123456"
  FEISHU_BUSINESS_APP_SECRET: Hg6F2UbXaSyumDNrQOiQ3gTBJiMbx2my
