apiVersion: v1
kind: ConfigMap
metadata:
  name: cron-service-config
  namespace: owl
data:
  NODE_ENV: production
  CRON_PORT: "3001"
  POSTGRES_HOST: 172.23.0.10
  POSTGRES_PORT: "5432"
  POSTGRES_USER: admin
  POSTGRES_DB: owl
  REDIS_HOST: 172.23.0.11
  REDIS_PORT: "6379"
  RABBITMQ_URL: amqp://admin:123456@172.23.0.12:5672
  FEISHU_BUSINESS_APP_ID: cli_a976e72a8a3cdbd0
