apiVersion: v1
kind: Secret
metadata:
    name: cron-service-secret
    namespace: owl
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:NBcfDE77ZxwvIeeQqNxoVq1M8S3C52Oxyf4U6Mf1+Ibgc9Od0+oo39Us56r1Q0CMLjEkhN+XVz45wxWk,iv:ynBMKCuvGbrgdzAVC3W5big1VYwrp026uVydQJSrZWk=,tag:Ufyay2ukrLLNNwntmptnCw==,type:str]
    FEISHU_BUSINESS_APP_SECRET: ENC[AES256_GCM,data:ZR7hcK91qYlaOPbDkTgiFn3Inz7LDdIcHBPLw1fpFnU=,iv:8KgBNsoc3AVGuDOz8r7e9J0smRLZOdSiI7bNN1P0ubU=,tag:je32kyMc9GwfBBCXGEnm9A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:AIWVYOUw,iv:nquHfi/JJyWOvOEF8xDMCRph9lMbKyWscM2niIGjGUk=,tag:UoocgNKytpUXZYEpmpbp1Q==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:cQ/wzRsk,iv:Lcd2e6cRppH1scD9YmvyK9jcNGmjFRInMSk/6YeECkk=,tag:wgn46yujTu/7F43EItMXYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTUlqdlhyKzRtb2FqOTQr
            YzBiVmh4TTEvWm1jS3ovL0EwUzdLd0xXSVcwCi9SSDUrKzFwYk9LZGtQRks4eUwv
            OWFTVFRKaTVRYjEzZm1XbXdQaHFKS0kKLS0tIENYcG9CM1p5YkI4NU1QZlBYWTJi
            cmh1d2ZLY2l4VlJMSkg2TkUvcW1KU0EK9l1zMX8xUZk38uMjpMfvPXs1p41E9tne
            UfZRkUl9QEAnVq5l4PmiKdSkDaJ8ZeIi9z/PQWDdnZ+i3TFEUo9dpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l9qlukrqgdcfvtenn5egqstw4l3lzlc8xup5p4l2vm9x0j84nqrqfaexhz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T06:23:19Z"
    mac: ENC[AES256_GCM,data:ru7iJ2j1qRnE/uoD1BAkP76sf2N2gVXhwi/HNy2yiNybQqxtoY4SlOKrP1WopZFxx9LflMMicGl1VzqeLtlT3z3eRPkimJfc73nRJsMfF8y5hjZJzTnA/7nvotM88/6mzx6tfVPDI9i9ryDEjeU0b5OwRYDlSUY4tgh1cdej1R4=,iv:7x+bHo4K0yZICyi4WPUMPQnuOGqSiBd9qXjjHbXlaI0=,tag:fpjB1CHOFYYlBAjGafcUQg==,type:str]
    version: 3.13.3
