server {
    listen 5273;
    server_name _;
    absolute_redirect off;

    root /usr/share/nginx/html;

    location = / {
        return 302 /owl/;
    }

    location /owl/ {
        try_files $uri $uri/ /owl/index.html;
    }

    location /owl/assets/ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
